- name: Install required software
  hosts: all
  become: true
  vars:
    airgapped: false

  tasks:
    - name: Enable dracut
      command: dracut -f
      become: yes

    - name: Skel initialization file permissions
      file:
        path: "/etc/skel/{{ item }}"
        mode: '0640'
      become: yes
      with_items:
        - ".bash_logout"
        - ".bash_profile"
        - ".bashrc"

    - name: Install remaining packages
      yum:
        name:
          - cloud-utils-growpart
          - unzip
          - wget
          - yum-utils
        state: latest
      become: yes
