
variable "aws_access_id" {
  type    = string
  default = "${env("AWS_ACCESS_ID")}"
}

variable "aws_secret_key" {
  type    = string
  default = "${env("AWS_SECRET_KEY")}"
}

variable "home" {
  type    = string
  default = "${env("HOME")}"
}

variable "iso_checksum" {
  type    = string
  default = "sha256:689531cce9cf484378481ae762fae362791a9be078fda10e4f6977bf8fa71350"
}

variable "iso_file" {
  type    = string
  default = "https://nexus.voight.org:9443/repository/MachineImages/base/centos/7/CentOS-7-x86_64-Everything-2009.iso"
}

variable "non_gui" {
  type    = string
  default = "true"
}

variable "password" {
  type    = string
  default = "${env("password")}"
}

variable "region" {
  type    = string
  default = "${env("AWS_DEFAULT_REGION")}"
}

variable "s3_bucket" {
  type    = string
  default = "iadsdo-tfstate"
}

variable "username" {
  type    = string
  default = "centos"
}

variable "vmname" {
  type    = string
  default = "rhel-7.9-x86_64"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command     = ["<up><tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"]
  boot_wait        = "10s"
  disk_size        = "49152"
  format           = "ova"
  guest_os_type    = "RedHat_64"
  headless         = true
  http_directory   = "http"
  iso_checksum     = "${var.iso_checksum}"
  iso_urls         = ["${var.iso_file}"]
  memory           = "8192"
  output_directory = "./builds"
  shutdown_command = "echo '${var.password}'|sudo -S /sbin/halt -h -p"
  ssh_password     = "${var.password}"
  ssh_port         = 22
  ssh_username     = "${var.username}"
  ssh_wait_timeout = "1800s"
  vboxmanage       = [["modifyvm", "{{ .Name }}", "--cpus", "2"], ["modifyvm", "{{ .Name }}", "--firmware", "BIOS"]]
  vm_name          = "${var.vmname}"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "file" {
    destination = "/home/centos/sudoers"
    source      = "files/sudoers"
  }

  provisioner "file" {
    destination = "/home/centos/cloud.cfg"
    source      = "files/cloud.cfg"
  }

  provisioner "file" {
    destination = "/home/centos/voight-ca.pem"
    source      = "files/voight-ca.pem"
  }

  provisioner "shell" {
    environment_vars = ["DNA=${var.iso_file}"]
    remote_folder    = "/home/centos"
    script           = "scripts/ansible.sh"
  }

  provisioner "ansible-local" {
    playbook_file = "scripts/init.yaml"
  }

  provisioner "shell" {
    remote_folder = "/home/centos"
    script        = "scripts/cleanup.sh"
  }

  post-processor "shell-local" {
    inline = ["cp -f builds/${var.vmname}.ova ${var.home}/Documents"]
  }

  post-processor "shell-local" {
    inline = ["sh -c 'scripts/install_image.sh ${var.vmname}.ova ${var.s3_bucket} Cu_RHEL_7.9_x86_64.ova'"]
  }
}
